name: Test mitoinstaller

on:
  push:
    branches: [ dev ]
    paths:
      - 'mitosheet/installer/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'mitosheet/installer/**'

jobs:
  test-mitoinstaller:
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd mitosheet/installer
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd mitosheet/installer
        pytest